import kotlinx.coroutines.runBlocking
import services.signal.SignalService

fun main(args: Array<String>) = runBlocking {
    val chatServices = listOf(
        SignalService("+12508807560")
    )
    // Start all chart services
    for (chatService in chatServices) {
        chatService.start(this)
        chatService.addMessageListener {
            // Don't respond to messages sent by the bot
            // Or reactions
            if (!it.fromBot && it.message != null) {
                // This is where we register commands
                if (it.message.lowercase().startsWith("!tldr")) {
                    chatService.sendMessage(it.conversationId, """
                    TLDR Command called
                    
                    This is an automatic response generated by TLDRer
                """.trimIndent())
                }
            }
        }
    }
}
